# Generated by Django 4.1.4 on 2023-01-02 16:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appUser', '0003_video'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Video',
        ),
    ]
